export enum CampaignErrorCode {
  ORGANIZATION_NOT_LABEL = 'ORGANIZATION_NOT_LABEL',
  INVALID_RITMO_FOR_GENRE = 'INVALID_RITMO_FOR_GENRE',
  CAMPAIGN_NOT_ACTIVE = 'CAMPAIGN_NOT_ACTIVE',
  COMPOSER_QUOTA_EXCEEDED = 'COMPOSER_QUOTA_EXCEEDED',
  TRACK_NOT_MATCHING = 'TRACK_NOT_MATCHING',
  DUPLICATE_SUBMISSION = 'DUPLICATE_SUBMISSION',
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  CAMPAIGN_NOT_CLOSED = 'CAMPAIGN_NOT_CLOSED',
}
