import { UserRole } from "src/users/entities/user-role.enum";

export const usersMock = [
  // ===== ADMIN (5) =====
  {
    name: "Ana",
    lastName: "Martínez",
    email: "ana.martinez.admin@example.com",
    password: "prueba123",
    role: UserRole.ADMIN,
    isVerified: true,
    countryCode: "+54",
    phone: "1123456789",
  },
  {
    name: "Carlos",
    lastName: "Pérez",
    email: "carlos.perez.admin@example.com",
    password: "prueba123",
    role: UserRole.ADMIN,
    isVerified: true,
    countryCode: "+54",
    phone: "1123456789",
  },
  {
    name: "Lucía",
    lastName: "Gómez",
    email: "lucia.gomez.admin@example.com",
    password: "prueba123",
    role: UserRole.ADMIN,
    isVerified: true,
    countryCode: "+54",
    phone: "1123456789",
  },
  {
    name: "Tomás",
    lastName: "Fernández",
    email: "tomas.fernandez.admin@example.com",
    password: "prueba123",
    role: UserRole.ADMIN,
    isVerified: false,
    countryCode: "+54",
    phone: "1123456789",
  },
  {
    name: "Valentina",
    lastName: "López",
    email: "valentina.lopez.admin@example.com",
    password: "prueba123",
    role: UserRole.ADMIN,
    isVerified: true,
    countryCode: "+54",
    phone: "1123456789",
  },

  // ===== AUTOR (5) =====
  {
    name: "Diego",
    lastName: "Suárez",
    email: "diego.suarez.autor@example.com",
    password: "prueba123",
    role: UserRole.AUTOR,
    biography: "Compositor de música clásica y experimental.",
    isVerified: true,
    countryCode: "+54",
    phone: "1123456789",
  },
  {
    name: "Micaela",
    lastName: "Rey",
    email: "micaela.rey.autor@example.com",
    password: "prueba123",
    role: UserRole.AUTOR,
    biography: "Autora de letras urbanas.",
    isVerified: false,
    countryCode: "+54",
    phone: "1123456789",
  },
  {
    name: "Santiago",
    lastName: "Domínguez",
    email: "santiago.dominguez.autor@example.com",
    password: "prueba123",
    role: UserRole.AUTOR,
    isVerified: true,
    countryCode: "+54",
    phone: "1123456789",
  },
  {
    name: "Julieta",
    lastName: "Alvarez",
    email: "julieta.alvarez.autor@example.com",
    password: "prueba123",
    role: UserRole.AUTOR,
    isVerified: false,
    countryCode: "+54",
    phone: "1123456789",
  },
  {
    name: "Federico",
    lastName: "Ortiz",
    email: "federico.ortiz.autor@example.com",
    password: "prueba123",
    role: UserRole.AUTOR,
    isVerified: true,
    countryCode: "+54",
    phone: "1123456789",
  },

  // ===== INTERPRETE (5) =====
  {
    name: "Marina",
    lastName: "Silva",
    email: "marina.silva.interprete@example.com",
    password: "prueba123",
    role: UserRole.INTERPRETE,
    isVerified: true,
    countryCode: "+54",
    phone: "1123456789",
  },
  {
    name: "Andrés",
    lastName: "Vega",
    email: "andres.vega.interprete@example.com",
    password: "prueba123",
    role: UserRole.INTERPRETE,
    isVerified: false,
    countryCode: "+54",
    phone: "1123456789",
  },
  {
    name: "Camila",
    lastName: "Morales",
    email: "camila.morales.interprete@example.com",
    password: "prueba123",
    role: UserRole.INTERPRETE,
    isVerified: true,
    countryCode: "+54",
    phone: "1123456789",
  },
  {
    name: "Javier",
    lastName: "Rojas",
    email: "javier.rojas.interprete@example.com",
    password: "prueba123",
    role: UserRole.INTERPRETE,
    isVerified: false,
    countryCode: "+54",
    phone: "1123456789",
  },
  {
    name: "Florencia",
    lastName: "Herrera",
    email: "florencia.herrera.interprete@example.com",
    password: "prueba123",
    role: UserRole.INTERPRETE,
    isVerified: true,
    countryCode: "+54",
    phone: "1123456789",
  },

  // ===== CANTAUTOR (5) =====
  {
    name: "Matías",
    lastName: "Aguilar",
    email: "matias.aguilar.cantautor@example.com",
    password: "prueba123",
    role: UserRole.CANTAUTOR,
    isVerified: true,
    countryCode: "+54",
    phone: "1123456789",
  },
  {
    name: "Sofía",
    lastName: "Navarro",
    email: "sofia.navarro.cantautor@example.com",
    password: "prueba123",
    role: UserRole.CANTAUTOR,
    isVerified: false,
    countryCode: "+54",
    phone: "1123456789",
  },
  {
    name: "Ignacio",
    lastName: "Torres",
    email: "ignacio.torres.cantautor@example.com",
    password: "prueba123",
    role: UserRole.CANTAUTOR,
    isVerified: true,
    countryCode: "+54",
    phone: "1123456789",
  },
  {
    name: "Paula",
    lastName: "Cruz",
    email: "paula.cruz.cantautor@example.com",
    password: "prueba123",
    role: UserRole.CANTAUTOR,
    isVerified: false,
    countryCode: "+54",
    phone: "1123456789",
  },
  {
    name: "Esteban",
    lastName: "Ramírez",
    email: "esteban.ramirez.cantautor@example.com",
    password: "prueba123",
    role: UserRole.CANTAUTOR,
    isVerified: true,
    countryCode: "+54",
    phone: "1123456789",
  },

  // ===== INVITADO (5) =====
  {
    name: "Daniela",
    lastName: "Mendoza",
    email: "daniela.mendoza.invitado@example.com",
    password: "prueba123",
    role: UserRole.INVITADO,
    isVerified: false,
    countryCode: "+54",
    phone: "1123456789",
  },
  {
    name: "Gabriel",
    lastName: "Sosa",
    email: "gabriel.sosa.invitado@example.com",
    password: "prueba123",
    role: UserRole.INVITADO,
    isVerified: false,
    countryCode: "+54",
    phone: "1123456789",
  },
  {
    name: "Laura",
    lastName: "Ibarra",
    email: "laura.ibarra.invitado@example.com",
    password: "prueba123",
    role: UserRole.INVITADO,
    isVerified: true,
    countryCode: "+54",
    phone: "1123456789",
  },
  {
    name: "Martín",
    lastName: "García",
    email: "martin.garcia.invitado@example.com",
    password: "prueba123",
    role: UserRole.INVITADO,
    isVerified: false,
    countryCode: "+54",
    phone: "1123456789",
  },
  {
    name: "Natalia",
    lastName: "Ponce",
    email: "natalia.ponce.invitado@example.com",
    password: "prueba123",
    role: UserRole.INVITADO,
    isVerified: true,
    countryCode: "+54",
    phone: "1123456789",
  },

  // ===== EDITOR (5) =====
  {
    name: "Rodrigo",
    lastName: "Flores",
    email: "rodrigo.flores.editor@example.com",
    password: "prueba123",
    role: UserRole.EDITOR,
    isVerified: true,
    countryCode: "+54",
    phone: "1123456789",
  },
  {
    name: "Carolina",
    lastName: "Muñoz",
    email: "carolina.munoz.editor@example.com",
    password: "prueba123",
    role: UserRole.EDITOR,
    isVerified: false,
    countryCode: "+54",
    phone: "1123456789",
  },
  {
    name: "Hernán",
    lastName: "Díaz",
    email: "hernan.diaz.editor@example.com",
    password: "prueba123",
    role: UserRole.EDITOR,
    isVerified: true,
    countryCode: "+54",
    phone: "1123456789",
  },
  {
    name: "Milagros",
    lastName: "Castro",
    email: "milagros.castro.editor@example.com",
    password: "prueba123",
    role: UserRole.EDITOR,
    isVerified: false,
    countryCode: "+54",
    phone: "1123456789",
  },
  {
    name: "Sebastián",
    lastName: "Correa",
    email: "sebastian.correa.editor@example.com",
    password: "prueba123",
    role: UserRole.EDITOR,
    isVerified: true,
    countryCode: "+54",
    phone: "1123456789",
  },
];
